require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - Guardfile

Style/Documentation:
  Enabled: false
